batch_size: 4
crop_size: 512
crop_size_depth: 32
early_stopping_patience: 0
finetuned_from: null
flow_loss_f: l1
heatmap_loss_f: bce
loss_levels: null
lr: 0.0003
lr_reduce_patience: 10
num_epochs: 200
num_train_samples: null
optimize_threshold: false
optimizer: adamw
pos_weight: 10.0
smart_crop: true
