[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "poufti"
version = "0.1.0"
description = "A high-throughput bacterial cell segmentation and locus tracking pipeline using Cellpose, Spotiflow, and Laptrack."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Liam McGoldrick", email = "lmcgo2@illinois.edu" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

dependencies = [
    "numpy",
    "pandas",
    "nd2",
    "cellpose==3.1.1.1",
    "spotiflow",
    "pyyaml",
    "tables",
    "shapely",
    "scipy",
    "laptrack",
    "ipython",
    "annotations",
]

[project.scripts]
poufti = "poufti.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]